apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=661013218527.dkr.ecr.us-east-1.amazonaws.com/node-app-jenkins2
    argocd-image-updater.argoproj.io/myapp.update-strategy: newest-build

    argocd-image-updater.argoproj.io/myapp.helm.image-spec: image.repository
    argocd-image-updater.argoproj.io/myapp.kustomize.image-name: node-app-jenkins2
spec:
  project: default
  source:
    repoURL: https://github.com/DanaMostafa48/GP-ITI.git
    targetRevision: HEAD
    path: kustomize/overlays
  destination:
    server: https://148DC3AB04B06BAA6607C6CEA4028F78.gr7.us-east-1.eks.amazonaws.com
    namespace: default
  syncPolicy:
    automated:
      prune: true  # Corrected here ArgoImageUpdaterECRPolicy
      selfHeal: true

