
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
stringData:
  ARGOCD_SERVER: https://argocd-server.argocd.svc:443
  ARGOCD_AUTH_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJpbWFnZS11cGRhdGVyOmFwaUtleSIsIm5iZiI6MTc0NjA5MDA1NSwiaWF0IjoxNzQ2MDkwMDU1LCJqdGkiOiJjN2EyOTEwYi00NmE0LTQ2OWEtYTkyZC01ZGFlOGFjMzcyOTIifQ.WKVS8vWJwtjmDrWprtNfLYDpEEyIU86s6vRwhbTkozo


#To get the ARGOCD_AUTH_TOKEN (used by Argo CD Image Updater to authenticate with Argo CD API), you need to log in to Argo CD and retrieve a token for a user or service account.