apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-image-updater  # Changed to match your Helm values
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::661013218527:role/argocd-ecr-access-role  # Matches your Terraform role