apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: nodejs-app
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/redis"
