apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: nodejs-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2  # Change this to the desired storage class
  hostPath:
    path: "/mnt/data/mysql"

