apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      serviceAccountName: external-secrets-sa
      containers:
        - name: nodejs-app
          image: yousra000/nodejs-mysql:latest
          ports:
            - containerPort: 3000
          env:
            - name: RDS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials22
                  key: hostname
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials22
                  key: username
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials22
                  key: password
            - name: RDS_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials22
                  key: port
            - name: REDIS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: redis-credentials22
                  key: hostname
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-credentials22
                  key: port
