apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argo-image-updater
data:
  interval: "2m"
  git.user: "ArgoCD Image Updater"
  git.email: "argocd-image-updater@example.com"
  log.level: "debug"
