apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-image-updater-binding
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater
    namespace: argo-image-updater
roleRef:
  kind: ClusterRole
  name: argocd-application-controller
  apiGroup: rbac.authorization.k8s.io