controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    pullPolicy: Always
    tag: "2.452.2-jdk21"

persistence:
  enabled: true
  storageClass: gp2  
  size: 8Gi


service:
  type: LoadBalancer
  port: 8080
